bbs-blog-master-master/bbs-blog-master/mybbs/urls.py
from django.conf.urls import url, include
from mybbs.views import login, register, check_code, logout

urlpatterns = [
    url(r'^$', login),
    url(r'^login/$', login),
    url(r'^register/$', register),
    url(r'^logout/$', logout),
    url(r'^check_code/$', check_code),
    url(r'^mainadmin/', include('mainadmin.urls')),
    url(r'^mainblog/', include('mainblog.urls')),
    url(r'^mainbbs/', include('mainbbs.urls')),
]

bbs-blog-master-master/bbs-blog-master/mainmodels/models.py
from django.db import models



class UserInfo(models.Model):
    """
    用户表
    """
    nid = models.BigAutoField(primary_key=True)
    username = models.CharField(verbose_name='用户名', max_length=32, unique=True)
    password = models.CharField(verbose_name='密码', max_length=64)
    nickname = models.CharField(verbose_name='昵称', max_length=32)
    gender = models.CharField(verbose_name='性别',max_length=2,default='男 ')
    email = models.EmailField(verbose_name='邮箱', unique=True)
    avatar = models.ImageField(verbose_name='头像')
    create_time = models.DateTimeField(verbose_name='创建时间')

    fans = models.ManyToManyField(verbose_name='粉丝们',
                                  to='UserInfo',
                                  through='UserFans',
                                  related_name='f',
                                  through_fields=('user', 'follower'))
class Blog(models.Model):
    """
    博客信息
    """
    fangwen = models.IntegerField(default=0)

    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name='个人博客标题', max_length=64)
    site = models.CharField(verbose_name='个人博客前缀', max_length=32, unique=True)
    theme = models.CharField(verbose_name='博客主题', max_length=32)
    user = models.OneToOneField(to='UserInfo', to_field='nid')


class UserFans(models.Model):
    """
    互粉关系表
    """
    user = models.ForeignKey(verbose_name='博主', to='UserInfo', to_field='nid', related_name='users',null=True)
    follower = models.ForeignKey(verbose_name='粉丝', to='UserInfo', to_field='nid', related_name='followers',null=True)

    class Meta:
        unique_together = [
            ('user', 'follower'),
        ]


class Category(models.Model):
    """
    博主个人文章分类表
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid')


class ArticleDetail(models.Model):
    """
    文章详细表
    """
    content = models.TextField(verbose_name='文章内容', )
    article = models.OneToOneField(verbose_name='所属文章', to='Article', to_field='nid')


class UpDown(models.Model):
    """
    文章顶或踩
    """
    article = models.ForeignKey(verbose_name='文章', to='Article', to_field='nid')
    user = models.ForeignKey(verbose_name='赞或踩用户', to='UserInfo', to_field='nid')
    up = models.BooleanField(verbose_name='是否赞')

    class Meta:
        unique_together = [
            ('article', 'user'),
        ]


class Comment(models.Model):
    """
    评论表
    """
    nid = models.BigAutoField(primary_key=True)
    content = models.CharField(verbose_name='评论内容', max_length=255)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    reply = models.ForeignKey(verbose_name='回复评论', to='self', related_name='back', null=True)
    article = models.ForeignKey(verbose_name='评论文章', to='Article', to_field='nid')
    user = models.ForeignKey(verbose_name='评论者', to='UserInfo', to_field='nid')
    reply_user_id = models.IntegerField(default=0)


class Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid')


class Article(models.Model):
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name='文章标题', max_length=128)
    summary = models.CharField(verbose_name='文章简介', max_length=255)
    read_count = models.IntegerField(default=0)
    comment_count = models.IntegerField(default=0)
    up_count = models.IntegerField(default=0)
    down_count = models.IntegerField(default=0)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid')
    category = models.ForeignKey(verbose_name='文章类型', to='Category', to_field='nid', null=True)
    tag = models.ForeignKey(verbose_name='标签类型', to='Tag', to_field='nid', null=True)

    type_choices = [
        (1, "Python"),
        (2, "Linux"),
        (3, "OpenStack"),
        (4, "Oracle"),
        (5, "Mysql"),
    ]

    article_type_id = models.IntegerField(choices=type_choices, default=None)

bbs-blog-master-master/bbs-blog-master/templates/admin_add_article.html
{% extends 'admin_layout.html' %}

{% block css %}
    <link rel="stylesheet" href="/static/plugins/kindeditor/themes/default/default.css"/>
    <style>
        .kind-content {
            width: 100%;
            min-height: 500px;
        }
    </style>
{% endblock %}

{% block content %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#">文章管理</a></li>
        <li class="active">添加文章</li>
    </ol>
    <div style="padding: 5px 8px;">
        <form method="POST" action="/mainadmin/add_article.html" novalidate>
            <div class="form-group">
                <label for="{{ form.title.id_for_label }}">标题 <span>{{ form.title.errors.0 }}</span></label>
                {{ form.title }}
            </div>
            <div class="form-group">
                <label for="summary">简介 <span>{{ form.summary.errors.0 }}</span></label>
                {{ form.summary }}
            </div>
            <div class="form-group">
                <label for="content">内容 <span>{{ form.content.errors.0 }}</span></label>
                {{ form.content }}
            </div>
            <div class="form-group">
                <label>类型 <span>{{ form.article_type_id.errors.0 }}</span></label>

                <div>
                    {{ form.article_type_id }}
                </div>
            </div>
            <div class="form-group">
                <label>分类 <span>{{ form.category_id.errors.0 }}</span></label>
                <div>
                    {{ form.category_id }}
                </div>
            </div>
            <div class="form-group">
                <label>标签 <span>{{ form.tags.errors.0 }}</span></label>

                <div>
                    {{ form.tag_id }}
                </div>
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="保 存">
            </div>
        </form>
    </div>


{% endblock %}

{% block js %}
    <script charset="utf-8" src="/static/plugins/kindeditor/kindeditor-min.js"></script>
    <script charset="utf-8" src="/static/plugins/kindeditor/lang/zh_CN.js"></script>
    <script>

        KindEditor.ready(function (K) {
            var editor = K.create('textarea[name="content"]', {
                resizeType: 1
            });
        });
         $(document).ready(function () {
                console.log({{  form.title.id_for_label }})

             });
    </script>
{% endblock %}

bbs-blog-master-master/bbs-blog-master/templates/admin_edit_category.html
{% extends 'admin_layout.html' %}
{% block css %}

{% endblock %}
{% block content %}
    <ol class="breadcrumb">
        <li><a href="#">分类管理</a></li>
        <li class="active">分类列表</li>
    </ol>
    <div>
        <div class="row" style="padding: 20px 5px;">
            <form class="form-horizontal">
                <div class="col-xs-12">
                    <div class="form-group">
                        <label class="col-xs-1 control-label">分类名称</label>

                        <div class="col-xs-3">
                            <input type="text" class="form-control" name="title" placeholder="请输入分类名称">
                        </div>
                        <div class="col-xs-3">
                            <input type="button" class="btn btn-primary" value="添 加" onclick="DoSubmit();">
                        </div>
                    </div>
                </div>
            </form>
        </div>

        <div style="height: 35px;background-color: #f5f5f5;line-height: 35px;padding: 0 15px;">
            <i class="fa fa-table" aria-hidden="true"></i>
            标签列表
        </div>

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>分类</th>
                    <th>文章个数</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                {% for item in ret %}
                    <tr>
                        <td class="hide nid">{{ item.nid }}</td>
                        <td id="title">{{ item.title }}</td>
                        <td>{{ item.blog_id }}</td>
                        <td>
                            <a class="btn btn-danger btn-xs">
                                删除
                            </a>
                            |
                            <a class="btn btn-primary btn-xs" href="update_category{{ item.nid }}.html">
                                编辑
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>


{% endblock %}

{% block js %}
    <script type="text/javascript">
        function DoSubmit() {
            var input_dic = {};
            $('input').each(function () {
                var v = $(this).val();
                var n = $(this).attr('name');
                input_dic[n] = v;
            });
            $.ajax({
                url:'/mainadmin/edit_category.html',
                type:'POST',
                data:input_dic,
                dataType: 'json',
                success: function (msg) {
                    if(msg.status){
                        location.href = '/mainadmin/edit_category.html'
                    }else{
                        alert(msg.message);
                    }

                }
            })
        }
        $('td a.btn.btn-danger.btn-xs').click(function () {
            var c_id = $(this).parent().siblings('.hide.nid').text();
            var c_dict = {};
            c_dict['nid'] = c_id;
            console.log(c_dict);
            $.ajax({
            url: '/mainadmin/edit_category.html',
            type: 'POST',
            data: c_dict,
            dataType: 'json',
            success: function (dmsg) {
                if(dmsg) {
                    location.href = '/mainadmin/edit_category.html'
                }
            }
          })
        })
    </script>
{% endblock %}

bbs-blog-master-master/bbs-blog-master/templates/admin_edit_tag.html
{% extends 'admin_layout.html' %}
{% block css %}

{% endblock %}
{% block content %}
    <ol class="breadcrumb">
        <li><a href="#">标签管理</a></li>
        <li class="active">标签列表</li>
    </ol>
    <div>
        <div class="row" style="padding: 20px 5px;">
            <form class="form-horizontal">
                <div class="col-xs-12">
                    <div class="form-group">
                        <label class="col-xs-1 control-label">标签名</label>
                        <div class="col-xs-3">
                            <input type="text" class="form-control" name="title" placeholder="请输入标签名">
                        </div>
                        <div class="col-xs-3">
                            <input type="button" class="btn btn-primary" value="添 加" onclick="DoSubmit();">
                        </div>
                    </div>
                </div>
            </form>
        </div>

        <div style="height: 35px;background-color: #f5f5f5;line-height: 35px;padding: 0 15px;">
            <i class="fa fa-table" aria-hidden="true"></i>
            标签列表
        </div>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>标签</th>
                <th>文章个数</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
                {% for item in ret %}
                    <tr>
                        <td class="hide nid">{{ item.nid }}</td>
                        <td id="title">{{ item.title }}</td>
                        <td>{{ item.blog_id }}</td>
                        <td>
                            <a class="btn btn-danger btn-xs">
                                删除
                            </a>
                            |
                            <a class="btn btn-primary btn-xs" href="update_tag{{ item.nid }}.html">
                                编辑
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>


{% endblock %}

{% block js %}
    <script type="text/javascript">
        function DoSubmit() {
            var input_dic = {};
            $('input').each(function () {
                var v = $(this).val();
                var n = $(this).attr('name');
                input_dic[n] = v;
            });
            console.log(input_dic)
            $.ajax({
                url:'/mainadmin/edit_tag.html',
                type:'POST',
                data:input_dic,
                dataType: 'json',
                success: function (msg) {
                    if(msg.status){
                        location.href = '/mainadmin/edit_tag.html'
                    }else{
                        alert(msg.message);
                    }

                }
            })
        }
        $('td a.btn.btn-danger.btn-xs').click(function () {
            var c_id = $(this).parent().siblings('.hide.nid').text();
            var c_dict = {};
            c_dict['nid'] = c_id;
            console.log(c_dict);
            $.ajax({
            url: '/mainadmin/edit_tag.html',
            type: 'POST',
            data: c_dict,
            dataType: 'json',
            success: function (dmsg) {
                if(dmsg) {
                    location.href = '/mainadmin/edit_tag.html'
                }
            }
          })
        })
    </script>
{% endblock %}

bbs-blog-master-master/bbs-blog-master/templates/admin_index.html
{% extends 'admin_layout.html' %}
{% block css %}

{% endblock %}
{% block content %}
   <h1>欢迎登陆：{{ request.session.user_info.username }}</h1>
{% endblock %}

{% block js %}

{% endblock %}

bbs-blog-master-master/bbs-blog-master/templates/admin_layout.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>后台管理</title>
    <!-- Bootstrap -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    {% block css %} {% endblock %}
    <style>
        #main-nav {
            margin-left: 1px;
        }

            #main-nav.nav-tabs.nav-stacked > li > a {
                padding: 10px 8px;
                font-size: 12px;
                font-weight: 600;
                color: #4A515B;
                background: #E9E9E9;
                background: -moz-linear-gradient(top, #FAFAFA 0%, #E9E9E9 100%);
                background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#FAFAFA), color-stop(100%,#E9E9E9));
                background: -webkit-linear-gradient(top, #FAFAFA 0%,#E9E9E9 100%);
                background: -o-linear-gradient(top, #FAFAFA 0%,#E9E9E9 100%);
                background: -ms-linear-gradient(top, #FAFAFA 0%,#E9E9E9 100%);
                background: linear-gradient(top, #FAFAFA 0%,#E9E9E9 100%);
                filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#FAFAFA', endColorstr='#E9E9E9');
                -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr='#FAFAFA', endColorstr='#E9E9E9')";
                border: 1px solid #D5D5D5;
                border-radius: 4px;
            }

                #main-nav.nav-tabs.nav-stacked > li > a > span {
                    color: #4A515B;
                }

                #main-nav.nav-tabs.nav-stacked > li.active > a, #main-nav.nav-tabs.nav-stacked > li > a:hover {
                    color: #FFF;
                    background: #3C4049;
                    background: -moz-linear-gradient(top, #4A515B 0%, #3C4049 100%);
                    background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#4A515B), color-stop(100%,#3C4049));
                    background: -webkit-linear-gradient(top, #4A515B 0%,#3C4049 100%);
                    background: -o-linear-gradient(top, #4A515B 0%,#3C4049 100%);
                    background: -ms-linear-gradient(top, #4A515B 0%,#3C4049 100%);
                    background: linear-gradient(top, #4A515B 0%,#3C4049 100%);
                    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#4A515B', endColorstr='#3C4049');
                    -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr='#4A515B', endColorstr='#3C4049')";
                    border-color: #2B2E33;
                }

                    #main-nav.nav-tabs.nav-stacked > li.active > a, #main-nav.nav-tabs.nav-stacked > li > a:hover > span {
                        color: #FFF;
                    }

            #main-nav.nav-tabs.nav-stacked > li {
                margin-bottom: 4px;
            }

        /*定义二级菜单样式*/
        .secondmenu a {
            font-size: 10px;
            color: #4A515B;
            text-align: center;
        }

        .navbar-static-top {
            background-color: #212121;
            margin-bottom: 5px;
        }

        .navbar-brand {
            background: url('') no-repeat 10px 8px;
            display: inline-block;
            vertical-align: middle;
            padding-left: 50px;
            color: #fff;
        }
    </style>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <!--导航栏-->
    <nav class="navbar navbar-inverse" role="navigation" style="background-color: #222">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">后台管理</a>
            </div>
        <div>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/mainbbs/bbs_index.html"><span class="glyphicon"></span> 论坛主页</a></li>
                <li><a href="/mainblog/blog_{{ blog_site }}.html"><span class="glyphicon"></span> 博客主页</a></li>
                <li><a href="/mainadmin/admin_index.html"><span class="glyphicon"></span> 后台主页</a></li>
            </ul>
        </div>
        </div>
    </nav>
    <!--左侧菜单栏-->
    <div class="row">
        <div class="col-md-2">
            <ul id="main-nav" class="nav nav-tabs nav-stacked" style="">
                <li>
                    <a href="edit_article_0_0.html">
                        <i class="glyphicon glyphicon-th-large"></i>
                        文章管理
                    </a>
                </li>
                <li>
                    <a href="edit_category.html">
                        <i class="glyphicon glyphicon-cog"></i>
                        分类管理
                    </a>
                </li>
                <li>
                    <a href="edit_tag.html">
                        <i class="glyphicon glyphicon-credit-card"></i>
                        标签管理
                    </a>
                </li>

                <li>
                    <a href="edit_base_info.html">
                        <i class="glyphicon glyphicon-globe"></i>
                        个人信息
                    </a>
                </li>
            </ul>
        </div>
        <div class="col-md-10">
            {% block content %} {% endblock %}
        </div>
    </div>
    
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="/static/js/jquery-2.1.4.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/static/js/bootstrap.min.js"></script>
    {% block js %}{% endblock %}
</body>
</html>

bbs-blog-master-master/bbs-blog-master/templates/admin_no_article.html
{% extends 'backend_layout.html' %}

{% block css %}
    <link rel="stylesheet" href="/static/plugins/kindeditor/themes/default/default.css"/>
    <style>
        .kind-content {
            width: 100%;
            min-height: 500px;
            visibility: hidden;
        }
    </style>
{% endblock %}

{% block conent %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#">文章管理</a></li>
        <li class="active">创建文章</li>
    </ol>
    <div style="padding: 5px 8px;">
        <h3>找不到文章...</h3>
    </div>


{% endblock %}

{% block js %}
    <script charset="utf-8" src="/static/plugins/kindeditor/kindeditor-min.js"></script>
    <script charset="utf-8" src="/static/plugins/kindeditor/lang/zh_CN.js"></script>
    <script>
        var editor;
        KindEditor.ready(function (K) {
            editor = K.create('textarea[name="content"]', {
                resizeType: 1,
                uploadJson: '/on.asp',
                fileManagerJson: '/asp/fjson.asp'
            });
        });
    </script>
{% endblock %}

bbs-blog-master-master/bbs-blog-master/templates/admin_update_article.html
{% extends 'admin_layout.html' %}

{% block css %}
    <link rel="stylesheet" href="/static/plugins/kindeditor/themes/default/default.css"/>
    <style>
        .kind-content {
            width: 100%;
            min-height: 500px;
        }
    </style>
{% endblock %}

{% block content %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#">文章管理</a></li>
        <li class="active">添加文章</li>
    </ol>
    <div style="padding: 5px 8px;">
        <form method="POST" action="/mainadmin/update_article{{ nid }}.html" novalidate>
            <div class="form-group">
                <label for="{{ form.title.id_for_label }}">标题 <span>{{ form.title.errors.0 }}</span></label>
                {{ form.title }}
            </div>
            <div class="form-group">
                <label for="summary">简介 <span>{{ form.summary.errors.0 }}</span></label>
                {{ form.summary }}
            </div>
            <div class="form-group">
                <label for="content">内容 <span>{{ form.content.errors.0 }}</span></label>
                {{ form.content }}
            </div>
            <div class="form-group">
                <label>类型 <span>{{ form.article_type_id.errors.0 }}</span></label>

                <div>
                    {{ form.article_type_id }}
                </div>

            </div>
            <div class="form-group">
                <label>分类 <span>{{ form.category_id.errors.0 }}</span></label>

                <div>
                    {{ form.category_id }}
                </div>
            </div>
            <div class="form-group">
                <label>标签 <span>{{ form.tags.errors.0 }}</span></label>

                <div>
                    {{ form.tag_id }}
                </div>
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="保 存">
            </div>
        </form>
    </div>


{% endblock %}

{% block js %}
    <script charset="utf-8" src="/static/plugins/kindeditor/kindeditor-min.js"></script>
    <script charset="utf-8" src="/static/plugins/kindeditor/lang/zh_CN.js"></script>
    <script>
        KindEditor.ready(function (K) {
            var editor = K.create('textarea[name="content"]', {
                resizeType: 1
            });
        });
    </script>
{% endblock %}

bbs-blog-master-master/bbs-blog-master/templates/blog_layout.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>博客</title>
    <link rel="stylesheet" href="/static/plugins/bootstrap/css/bootstrap.css"/>
    <link rel="stylesheet" href="/static/plugins/font-awesome/css/font-awesome.css"/>
    <link rel="stylesheet" href="/static/css/edmure.css"/>
    <link rel="stylesheet" href="/static/css/commons.css"/>
    <link rel="stylesheet" href="/static/css/row-avatar.css"/>
    <link rel="stylesheet" href="/static/css/theme/{{ blog.theme }}.css"/>
    {% block css %}{% endblock %}
    <script type="text/javascript" src="/static/js/jquery-2.1.4.min.js"></script>
    <script type="text/javascript" src="/static/plugins/bootstrap/js/bootstrap.js"></script>
</head>
<body>
<div class="pg-header">
    <div class="title">{{ blog.title }}</div>
    <div class="menu-list">
        <a class="menu-item" href="/mainbbs/bbs_index.html">论坛首页</a>
        {% if request.session.user_info.blog__site %}
            <a class="menu-item" href="/mainblog/blog_{{ request.session.user_info.blog__site }}.html">个人首页</a>
            <a class="menu-item" href="/mainadmin/admin_index.html">后台管理</a>
            <a class="menu-item"
               href="/mainblog/blog_{{ request.session.user_info.blog__site }}.html">欢迎{{ request.session.user_info.nickname }}</a>
        {% else %}
            <a class="menu-item" href="#">个人首页</a>
            <a class="menu-item" href="#">后台管理</a>
        {% endif %}
    </div>
</div>
<div class="pg-body">
    <div class="body-menu">
        <div class="notice">
            <div class="notice-header">公告</div>
            <div class="notice-body">
                  {% if request.session.user_info.nid !=  blog.user.nid %}
                <ul>
                    <li>昵称：{{ blog.user.nickname }}</li>
                    <li>粉丝：{{ blog.user.fans.count }}</li>
                    <li>关注：{{ blog.user.f.count }}</li>
                    <li>邮箱：{{ blog.user.email }}</li>
                </ul>
            {% else %}
             <ul>
                    <li>昵称：{{ blog.user.nickname }}</li>
                    <li>粉丝：{{ blog.user.fans.count }}</li>
                    <li>关注：{{ blog.user.f.count }}</li>
                    <li>邮箱：{{ blog.user.email }}</li>
                    <li>当日访问量：{{ sum1 }}</li>
                    <li>总访问量：{{ blog.fangwen}}</li>
                </ul>

            {% endif %}
                {% if request.session.user_info.nid !=  blog.user.nid %}
                {% if add > 0 %}
                    <a name="quxiaoguanzhu" class="{{ blog.user.nid }} {{ request.session.user_info.nid }}">
                        <text>取消关注ta!</text>
                        <i class="fa fa-heart" aria-hidden="true"></i>
                    </a>
                {% else %}
                    {% csrf_token %}

                    <a name="guanzhu" class="{{ blog.user.nid }} {{ request.session.user_info.nid }}">
                        <text> 双击关注ta!</text>
                        <i class="fa fa-heart-o" aria-hidden="true"></i>
                    </a>
                {% endif %}
            {% endif %}
                <div class="memo">
                    心忧柴米油盐，不忘仰望星空。
                </div>
            </div>
        </div>
        <div class="tags">
            <div class="tags-header">标签</div>
            <div class="tags-body">
                <ul>
                    {% for tag in tag_list %}
                        <li>
                            <a href="/mainblog/{{ blog.site }}/tag/{{ tag.nid }}.html">{{ tag.title }}({{ tag.article_set.count }})</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="types">
            <div class="types-header">分类</div>
            <div class="types-body">
                <ul>
                    {% for tag in category_list %}
                        <li>
                            <a href="/mainblog/{{ blog.site }}/category/{{ tag.nid }}.html">{{ tag.title }}({{ tag.article_set.count }})</a>
                        </li>
                    {% endfor %}
                </ul>

            </div>
        </div>
        <div class="dates">
            <div class="dates-header">时间</div>
            <div class="dates-body">
                <ul>
                    {% for tag in date_list %}
                        <li><a href="/mainblog/{{ blog.site }}/date/{{ tag.2 }}.html">{{ tag.2 }}({{ tag.1 }})</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <div class="body-content">
        {% block content %}{% endblock %}
    </div>
</div>
{% block js %}{% endblock %}
{% block guanzhuan %}
<script src="/static/js/jquery-2.1.4.min.js"></script>
<script>
    $(document).ready(function () {
        var b ={{request.session.user_info.nid}}
        var input = {b};
        $.ajax({
            url: '/mainblog/blog_{{ blog.user.username }}.html',
            type: 'POST',
            data: input,
            dataType: 'json',
            success: function (msg) {
                if (msg.status) {
                    location.href = '/mainblog/blog_{{ blog.user.username }}.html'
                } else {
                    alert(msg.message);
                }
            }
        })

    });
        $("a[name='guanzhu']").click(function () {
            var v = $(this).attr('class');
            var input_dic = {};
            input_dic['guanzhu'] = v;
            console.log(input_dic);

            $.ajax({
                url: '/mainblog/blog_{{ blog.user.username }}.html',
                type: 'POST',
                data: input_dic,
                dataType: 'json',
                success: function (msg) {
                    if (msg.status) {
                        location.href = '/mainblog/blog_{{ blog.user.username }}.html'
                         location.reload()
                    } else {
                        alert(msg.message);
                    }
                }
            })

        });
        $("a[name='quxiaoguanzhu']").click(function () {
            var v = $(this).attr('class');
            var input_dic = {};
            input_dic['quxiao'] = v;
            console.log(input_dic);
            $.ajax({
                url: '/mainblog/blog_{{ blog.user.username }}.html',
                type: 'POST',
                data: input_dic,
                dataType: 'json',
                success: function (msg) {
                    if (msg.status) {
                        location.href = '/mainblog/blog_{{ blog.user.username }}.html'
                    } else {
                        alert(msg.message);
                    }
                }
            })

         });

</script>
{% endblock %}
</body>
</html>